global:
    scrape_interval: 5s

scrape_configs:
    - job_name: Prometheus
      static_configs:
        - targets: ['localhost:9090']

    - job_name: Node
      static_configs:
        - targets: ['localhost:9100']
